jobs:
  tests:
  run-on: ubuntu-latest

steps:
  - name: Checkour repository
    uses: actions/checkout@v3

  - name: Build and start services
    run: docker-compose up -d --build  # 👈 Ensures dependencies are installed

  - name: Run tests inside container
    run: docker compose exec app npm test

  - name: Stop and remove containers
    run: docker compose down